import Header from "./components/Header/Header";
import "./globals.css";
import { Ubuntu } from "next/font/google";
const font = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "BAKESPACE | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
