import Header from "./components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "BAKESPACE | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
