"use client";
import Header from "./components/Header/Header";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "BAKESPACE | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className="flex flex-col min-h-[100vh]">
          <div>{children}</div>
        </body>
      </SessionProvider>
    </html>
  );
}
