"use client";
import SlideBar from "../components/slideBar/SlideBar";
import "../globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "BAKESPACE | dashboard",
  description: "Generated by create next app",
};

export default function dashboardlayout({ children }) {
  return (
    <SessionProvider>
      <div className="flex w-[100%] mt-[70px]">
        <SlideBar />

        {children}
      </div>
    </SessionProvider>
  );
}
