import SlideBar from "../components/slideBar/SlideBar";
import "../globals.css";

export const metadata = {
  title: "BAKESPACE | dashboard",
  description: "Generated by create next app",
};

export default function dashboardlayout({ children }) {
  return (
    <div className="flex w-[100%] min-h-screen mt-[70px] justify-center items-center ">
      <SlideBar />

      {children}
    </div>
  );
}
