import SlideBar from "../components/slideBar/SlideBar";
import "../globals.css";

export const metadata = {
  title: "BAKESPACE | dashboard",
  description: "Generated by create next app",
};

export default function dashboardlayout({ children }) {
  return (
    <div className="flex w-[100%] mt-[70px]">
      <SlideBar />

      {children}
    </div>
  );
}
